image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  DOCKER_DRIVER: overlay

release:
  stage: build
  script:
    - docker build -t dxcrepo.azurecr.io/certificat-service ./certificat
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REPOSIROTY --username $DOCKER_USERNAME --password-stdin
    - docker push dxcrepo.azurecr.io/certificat-service
