image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  DOCKER_DRIVER: overlay

release:
  stage: build
  script:
    - docker build -t $DOCKER_REPOSITORY/certificat-service:latest ./certificat
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REPOSITORY --username $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY/certificat-service:latest
