image: docker:latest
services:
- docker:dind

stages:
- build competance
- build front

variables:
  DOCKER_DRIVER: overlay

release:
  stage: build competance
  script:
    - docker build -t $DOCKER_REPOSITORY/microservice-competance:latest ./competance
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REPOSITORY --username $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY/microservice-competance:latest
  only:
    - main

build:
  stage: build front
  script:
    - docker build -t $DOCKER_REPOSITORY/dxc-repo:latest ./dxc-repo
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REPOSITORY --username $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY/dxc-repo:latest
  only:
    - main


