image: docker:latest
services:
- docker:dind

stages:
- build competance

variables:
  DOCKER_DRIVER: overlay

release:
  stage: build competance
  script:
    - docker build -t $DOCKER_REPOSITORY/microservice-competance:latest ./competance
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REPOSITORY --username $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY/microservice-competance:latest
  only:
    - main



