export const VALIDATE_FORM = "VALIDATE_FORM";
export const VALIDATE_FORM_SUCCESS = "VALIDATE_FORM_SUCCESS";
export const VALIDATE_FORM_ERROR = "VALIDATE_FORM_ERROR";

//RESSOURCE
export const SHOW_ID_RESSOURCE = "SHOW_ID_RESSOURCE";

export const ADD_RESSOURCE = "ADD_RESSOURCE";
export const ADD_RESSOURCE_SUCCESS = "ADD_RESSOURCE_SUCCESS";
export const ADD_RESSOURCE_ERROR = "ADD_RESSOURCE_ERROR";

export const START_DOWNLOAD_RESSOURCES = "START_DOWNLOAD_RESSOURCES";
export const RESSOURCE_DOWNLOAD_SUCCESSFUL = "START_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_RESSOURCE__ERROR = "START_DOWNLOAD_ERROR";

export const GET_RESSOURCE_REMOVE = "GET_RESSOURCE_REMOVE";
export const DELETE_RESSOURCE_SUCCESS = "DELETE_RESSOURCE_SUCCESS";
export const DELETE_RESSOURCE_ERROR = "DELETE_RESSOURCE_ERROR";

export const GET_RESSOURCE_EDIT = "GET_RESSOURCE_EDIT";
export const RESSOURCE_EDIT_SUCCESS = "RESSOURCE_EDIT_SUCCESS";
export const RESSOURCE_EDIT_ERROR = "RESSOURCE_EDIT_ERROR";

export const BEGIN_RESSOURCE_EDIT = "BEGIN_RESSOURCE_EDIT";
export const EDITION_RESSOURCE_SUCCESS = "EDITION_RESSOURCE_SUCCESS";
export const EDIT_RESSOURCE_ERROR = "EDIT_RESSOURCE_ERROR";

//prestations
export const ADD_PRESTATION = "ADD_PRESTATION";
export const ADD_PRESTATION_SUCCESS = "ADD_PRESTATION_SUCCESS";
export const ADD_PRESTATION_ERROR = "ADD_PRESTATION_ERROR";

export const BEGIN_PRESTATION_EDIT = "BEGIN_PRESTATION_EDIT";
export const EDITION_PRESTATION_SUCCESS = "EDITION_PRESTATION_SUCCESS";
export const EDIT_PRESTATION_ERROR = "EDIT_PRESTATION_ERROR";

export const START_DOWNLOAD_PRESTATIONS = "START_DOWNLOAD_PRESTATIONS";
export const PRESTATION_DOWNLOAD_SUCCESSFUL = "PRESTATION_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_PRESTATION__ERROR = "DOWNLOAD_PRESTATION__ERROR";

export const GET_PRESTATION_EDIT = "GET_PRESTATION_EDIT";
export const PRESTATION_EDIT_SUCCESS = "PRESTATION_EDIT_SUCCESS";
export const PRESTATION_EDIT_ERROR = "PRESTATION_EDIT_ERROR";
export const SHOWRESSOURCES = "SHOWRESSOURCES";

//certifications
export const ADD_CERTIFICATION = "ADD_CERTIFICATION";
export const ADD_CERTIFICATION_SUCCESS = "ADD_CERTIFICATION_SUCCESS";
export const ADD_CERTIFICATION_ERROR = "ADD_CERTIFICATION_ERROR";

export const BEGIN_CERTIFICATION_EDIT = "BEGIN_CERTIFICATION_EDIT";
export const EDITION_CERTIFICATION_SUCCESS = "EDITION_CERTIFICATION_SUCCESS";
export const EDIT_CERTIFICATION_ERROR = "EDIT_CERTIFICATION_ERROR";

export const START_DOWNLOAD_CERTIFICATIONS = "START_DOWNLOAD_CERTIFICATIONS";
export const CERTIFICATION_DOWNLOAD_SUCCESSFUL =
  "CERTIFICATION_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_CERTIFICATION__ERROR = "DOWNLOAD_CERTIFICATION__ERROR";

export const GET_CERTIFICATION_EDIT = "GET_CERTIFICATION_EDIT";
export const CERTIFICATION_EDIT_SUCCESS = "CERTIFICATION_EDIT_SUCCESS";
export const CERTIFICATION_EDIT_ERROR = "CERTIFICATION_EDIT_ERROR";

// export const GET_CERTIFICATION_EDIT = "GET_CERTIFICATION_EDIT";
// export const CERTIFICATION_EDIT_SUCCESS = "CERTIFICATION_EDIT_SUCCESS";
// export const CERTIFICATION_EDIT_ERROR = "CERTIFICATION_EDIT_ERROR";

// Contrats

// actions pour créer un contrat
export const ADD_CONTRAT = "ADD_CONTRAT";
export const ADD_CONTRAT_SUCCESS = "ADD_CONTRAT_SUCCESS";
export const ADD_CONTRAT_ERROR = "ADD_CONTRAT_ERROR";

// actions pour télécharger des contrats
export const START_DOWNLOAD_CONTRATS = "START_DOWNLOAD_CONTRATS";
export const CONTRAT_DOWNLOAD_SUCCESSFUL = "START_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_CONTRAT__ERROR = "START_DOWNLOAD_ERROR";

//actions pour la modification d'un contrat
export const GET_CONTRAT_EDIT = "GET_CONTRAT_EDIT";
export const CONTRAT_EDIT_SUCCESS = "CONTRAT_EDIT_SUCCESS";
export const CONTRAT_EDIT_ERROR = "CONTRAT_EDIT_ERROR";

// lorsque nous appuyons sur le bouton enregistrer les modification d'un contrat
export const BEGIN_CONTRAT_EDIT = "BEGIN_CONTRAT_EDIT";
export const EDITION_CONTRAT_SUCCESS = "EDITION_CONTRAT_SUCCESS";
export const EDIT_CONTRAT_ERROR = "EDIT_CONTRAT_ERROR";

// clients
// actions pour créer un client
export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_ERROR = "ADD_CLIENT_ERROR";

// actions pour télécharger des clients
export const START_DOWNLOAD_CLIENTS = "START_DOWNLOAD_CLIENTS";
export const CLIENT_DOWNLOAD_SUCCESSFUL = "START_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_CLIENT__ERROR = "START_DOWNLOAD_ERROR";

//actions pour la modification d'un client
export const GET_CLIENT_EDIT = "GET_CLIENT_EDIT";
export const CLIENT_EDIT_SUCCESS = "CLIENT_EDIT_SUCCESS";
export const CLIENT_EDIT_ERROR = "CLIENT_EDIT_ERROR";

// lorsque nous appuyons sur le bouton enregistrer les modification d'un client
export const BEGIN_CLIENT_EDIT = "BEGIN_CLIENT_EDIT";
export const EDITION_CLIENT_SUCCESS = "EDITION_CLIENT_SUCCESS";
export const EDIT_CLIENT_ERROR = "EDIT_CLIENT_ERROR";

// competances
export const SHOW_COMPETANCE_ID_RESSOURCE = "SHOW_COMPETANCE_ID_RESSOURCE";
// actions pour créer une competance
export const ADD_COMPETANCE = "ADD_COMPETANCE";
export const ADD_COMPETANCE_SUCCESS = "ADD_COMPETANCE_SUCCESS";
export const ADD_COMPETANCE_ERROR = "ADD_COMPETANCE_ERROR";

// actions pour télécharger des competances
export const START_DOWNLOAD_COMPETANCES = "START_DOWNLOAD_COMPETANCES";
export const COMPETANCE_DOWNLOAD_SUCCESSFUL = "START_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_COMPETANCE__ERROR = "START_DOWNLOAD_ERROR";

//actions pour la modification d'une competance
export const GET_COMPETANCE_EDIT = "GET_COMPETANCE_EDIT";
export const COMPETANCE_EDIT_SUCCESS = "COMPETANCE_EDIT_SUCCESS";
export const COMPETANCE_EDIT_ERROR = "COMPETANCE_EDIT_ERROR";

// lorsque nous appuyons sur le bouton enregistrer les modification d'une competance
export const BEGIN_COMPETANCE_EDIT = "BEGIN_COMPETANCE_EDIT";
export const EDITION_COMPETANCE_SUCCESS = "EDITION_COMPETANCE_SUCCESS";
export const EDIT_COMPETANCE_ERROR = "EDIT_COMPETANCE_ERROR";

// activites
export const ADD_ACTIVITE = "ADD_ACTIVITE";
export const ADD_ACTIVITE_SUCCESS = "ADD_ACTIVITE_SUCCESS";
export const ADD_ACTIVITE_ERROR = "ADD_ACTIVITE_ERROR";

// actions pour télécharger des ACTIVITEs
export const START_DOWNLOAD_ACTIVITES = "START_DOWNLOAD_ACTIVITES";
export const ACTIVITE_DOWNLOAD_SUCCESSFUL = "START_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_ACTIVITE__ERROR = "START_DOWNLOAD_ERROR";

//actions pour la modification d'une ACTIVITE
export const GET_ACTIVITE_EDIT = "GET_ACTIVITE_EDIT";
export const ACTIVITE_EDIT_SUCCESS = "ACTIVITE_EDIT_SUCCESS";
export const ACTIVITE_EDIT_ERROR = "ACTIVITE_EDIT_ERROR";

// lorsque nous appuyons sur le bouton enregistrer les modification d'une ACTIVITE
export const BEGIN_ACTIVITE_EDIT = "BEGIN_ACTIVITE_EDIT";
export const EDITION_ACTIVITE_SUCCESS = "EDITION_ACTIVITE_SUCCESS";
export const EDIT_ACTIVITE_ERROR = "EDIT_ACTIVITE_ERROR";
