export const VALIDATE_FORM = "VALIDATE_FORM";
export const VALIDATE_FORM_SUCCESS = "VALIDATE_FORM_SUCCESS";
export const VALIDATE_FORM_ERROR = "VALIDATE_FORM_ERROR";

//acciones para crear producto
export const ADD_RESSOURCE = "ADD_RESSOURCE";
export const ADD_RESSOURCE_SUCCESS = "ADD_RESSOURCE_SUCCESS";
export const ADD_RESSOURCE_ERROR = "ADD_RESSOURCE_ERROR";

export const ADD_PRESTATION = "ADD_PRESTATION";
export const ADD_PRESTATION_SUCCESS = "ADD_PRESTATION_SUCCESS";
export const ADD_PRESTATION_ERROR = "ADD_PRESTATION_ERROR";

export const BEGIN_PRESTATION_EDIT = "BEGIN_PRESTATION_EDIT";
export const EDITION_PRESTATION_SUCCESS = "EDITION_PRESTATION_SUCCESS";
export const EDIT_PRESTATION_ERROR = "EDIT_PRESTATION_ERROR";

//acciones para descargar productos
export const START_DOWNLOAD_RESSOURCES = "START_DOWNLOAD_RESSOURCES";
export const RESSOURCE_DOWNLOAD_SUCCESSFUL = "RESSOURCE_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_RESSOURCE__ERROR = "START_DOWNLOAD_ERROR";

export const START_DOWNLOAD_PRESTATIONS = "START_DOWNLOAD_PRESTATIONS";
export const PRESTATION_DOWNLOAD_SUCCESSFUL = "PRESTATION_DOWNLOAD_SUCCESSFUL";
export const DOWNLOAD_PRESTATION__ERROR = "DOWNLOAD_PRESTATION__ERROR";

//acciones para la eliminacion

export const GET_RESSOURCE_REMOVE = "GET_RESSOURCE_REMOVE";
export const DELETE_RESSOURCE_SUCCESS = "DELETE_RESSOURCE_SUCCESS";
export const DELETE_RESSOURCE_ERROR = "DELETE_RESSOURCE_ERROR";

//acciones para producto editar
export const GET_RESSOURCE_EDIT = "GET_RESSOURCE_EDIT";
export const RESSOURCE_EDIT_SUCCESS = "RESSOURCE_EDIT_SUCCESS";
export const RESSOURCE_EDIT_ERROR = "RESSOURCE_EDIT_ERROR";

//CUANDO PRECIONEMOS EL BOTON DE GUARDAR CAMBIOS
export const BEGIN_RESSOURCE_EDIT = "BEGIN_RESSOURCE_EDIT";
export const EDITION_RESSOURCE_SUCCESS = "EDITION_RESSOURCE_SUCCESS";
export const EDIT_RESSOURCE_ERROR = "EDIT_RESSOURCE_ERROR";
